FROM node:22-bookworm

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY tsconfig.json ./
COPY src ./src

RUN npm run build

ENV NODE_ENV=production
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

RUN npm ci --omit=dev

RUN npx playwright install --with-deps chromium \
    && chmod -R 777 /ms-playwright

USER node

CMD ["node", "dist/scanner-entry.js"]